# name: deploy-v8json

# on:
#   push:
#     branches: [main]

# jobs:
#   build_publish:
#     name: deploy v8.json
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Deploy style spec
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./src/style-spec/reference
#           publish_branch: gh-pages-public
